[palettes.custom]
bg = "#121212"
mantle = "#1a1a1a"
crust = "#0a0a0a"
surface0 = "#262626"
surface1 = "#383838"
surface2 = "#4e4e4e"
overlay0 = "#757575"
text = "#f5f5f5"
subtext = "#c2c2c2"
lavender = "#e0e0e0"
mauve = "#e0e0e0"
blue = "#ffffff"
red = "#d6d6d6"
green = "#ffffff"
yellow = "#e8e8e8"
