[palettes.custom]
bg = "#282828"
mantle = "#1d2021"
crust = "#141617"
surface0 = "#3c3836"
surface1 = "#504945"
surface2 = "#665c54"
overlay0 = "#928374"
text = "#ebdbb2"
subtext = "#d5c4a1"
lavender = "#d3869b"
mauve = "#b16286"
blue = "#fe8019"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
