[palettes.custom]
bg = "#282c34"
mantle = "#21252b"
crust = "#1b1d23"
surface0 = "#2c313c"
surface1 = "#3e4451"
surface2 = "#4b5263"
overlay0 = "#5c6370"
text = "#abb2bf"
subtext = "#828997"
lavender = "#c678dd"
mauve = "#c678dd"
blue = "#61afef"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
