[palettes.custom]
bg = "#191724"
mantle = "#1f1d2e"
crust = "#14131e"
surface0 = "#26233a"
surface1 = "#312f44"
surface2 = "#403d52"
overlay0 = "#6e6a86"
text = "#e0def4"
subtext = "#908caa"
lavender = "#c4a7e7"
mauve = "#ebbcba"
blue = "#ebbcba"
red = "#eb6f92"
green = "#9ccfd8"
yellow = "#f6c177"
