-- Safe check to load colors generated by Matugen
local status, colors = pcall(require, "lua.matugen_colors")
local use_matugen = status and type(colors) == "table" and colors.primary ~= nil

hl.config({
    gestures = {
        workspace_swipe_distance = 700,
        workspace_swipe_cancel_ratio = 0.2,
        workspace_swipe_min_speed_to_force = 5,
        workspace_swipe_direction_lock = true,
        workspace_swipe_direction_lock_threshold = 10,
        workspace_swipe_create_new = true
    },
    general = {
        -- Gaps and border
        gaps_in = 6,
        gaps_out = 10,
        gaps_workspaces = 20,

        border_size = 0,

        col = {
            active_border = use_matugen and colors.primary or "rgba(0DB7D455)",
            inactive_border = use_matugen and colors.outline or "rgba(31313600)"
        },
        resize_on_border = true,

        no_focus_fallback = true,
        allow_tearing = true, -- This just allows the `immediate` window rule to work
        -- snap = {
        --     enabled = true,
        --     window_gap = 4,
        --     monitor_gap = 5,
        --     respect_gaps = true
        -- }
    },
    decoration = {
        -- 2 = circle, higher = squircle, 4 = very obvious squircle
        -- Fuck clearly visible squircles. 100% Apple brainrot.
        rounding_power = 2.5,
        rounding = 18,

		active_opacity = 0.95,
		inactive_opacity = 0.90,


        blur = {
            enabled = true,
            xray = false,
            special = false,
            new_optimizations = true,
            size = 20,
            passes = 4,
            brightness = 1,
            noise = 0.05,
            contrast = 0.89,
            vibrancy = 0.5,
            vibrancy_darkness = 0.5,
            popups = false,
            popups_ignorealpha = 0.6,
            input_methods = true,
            input_methods_ignorealpha = 0.8
        },
        shadow = {
            enabled = true,
            range = 25,
            render_power = 4,
            color = "rgba(1a1a1aee)"
		},
        -- Dim
        dim_inactive = true,
        dim_strength = 0.05,
        dim_special = 0.2
    },
    animations = {
        enabled = true
    },
    dwindle = {
        preserve_split = true,
        smart_split = false,
        smart_resizing = false
        -- precise_mouse_move = true,
    },
})

