[palettes.custom]
bg = "#282a36"
mantle = "#21222c"
crust = "#191a21"
surface0 = "#343746"
surface1 = "#44475a"
surface2 = "#6272a4"
overlay0 = "#6272a4"
text = "#f8f8f2"
subtext = "#bfbfbf"
lavender = "#bd93f9"
mauve = "#ff79c6"
blue = "#8be9fd"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
