[palettes.custom]
bg = "#2e3440"
mantle = "#272c36"
crust = "#21252d"
surface0 = "#3b4252"
surface1 = "#434c5e"
surface2 = "#4c566a"
overlay0 = "#616e88"
text = "#eceff4"
subtext = "#e5e9f0"
lavender = "#b48ead"
mauve = "#b48ead"
blue = "#88c0d0"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
