# Monokai Pro Palette for Kitty
background            #282936
foreground            #fdfdfd
cursor                #ffd866
cursor_text_color     #282936
selection_background  #3a3b4e
selection_foreground  #fdfdfd

url_color             #78dce8

active_border_color     #ffd866
inactive_border_color   #494a5a
bell_border_color       #fc9867

active_tab_foreground   #1e1f29
active_tab_background   #ffd866
inactive_tab_foreground #fdfdfd
inactive_tab_background #282936
tab_bar_background      #1e1f29

# black
color0 #282936
color8 #727072

# red
color1 #ff6188
color9 #ff6188

# green
color2  #a9dc76
color10 #a9dc76

# yellow
color3  #ffd866
color11 #ffd866

# blue
color4  #fc9867
color12 #fc9867

# magenta
color5  #ab9df2
color13 #ab9df2

# cyan
color6  #78dce8
color14 #78dce8

# white
color7  #e3e3e1
color15 #fdfdfd
