[palettes.custom]
bg = "#2d2a2e"
mantle = "#221f22"
crust = "#19181a"
surface0 = "#3a383c"
surface1 = "#403e41"
surface2 = "#5b595c"
overlay0 = "#727072"
text = "#fcfcfa"
subtext = "#c1c0c0"
lavender = "#ab9df2"
mauve = "#ab9df2"
blue = "#ffd866"
red = "#ff6188"
green = "#a9dc76"
yellow = "#ffd866"
