# Ayu Mirage Palette for Kitty
background            #1f2430
foreground            #cbccc6
cursor                #ffcc66
cursor_text_color     #1f2430
selection_background  #343f4c
selection_foreground  #cbccc6

url_color             #73d0ff

active_border_color     #ffb454
inactive_border_color   #404d60
bell_border_color       #ffd580

active_tab_foreground   #0f141c
active_tab_background   #ffb454
inactive_tab_foreground #cbccc6
inactive_tab_background #1f2430
tab_bar_background      #0f141c

# black
color0 #191e2a
color8 #686868

# red
color1 #ed8274
color9 #f28779

# green
color2  #a6cc70
color10 #bae67e

# yellow
color3  #fad07b
color11 #ffd580

# blue
color4  #6dcbfa
color12 #73d0ff

# magenta
color5  #cfbafa
color13 #d4bfff

# cyan
color6  #90e1c6
color14 #95e6cb

# white
color7  #c7c7c7
color15 #ffffff
