[palettes.custom]
bg = "#1f2430"
mantle = "#191e2a"
crust = "#141925"
surface0 = "#232834"
surface1 = "#2d3343"
surface2 = "#3e4659"
overlay0 = "#707a8c"
text = "#cbccc6"
subtext = "#a0a7b4"
lavender = "#d4bfff"
mauve = "#d4bfff"
blue = "#73d0ff"
red = "#f28779"
green = "#bae67e"
yellow = "#ffcc66"
